# Generated by Django 4.1.2 on 2022-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.CharField(max_length=3),
        ),
    ]
